### ISSUE TITLE
Allow +1, share by twitter, diaspora, status.net, etc..

### ISSUE THREAD

**Issue by xray7224** [dandart/projectchaplin#16]
Having some awesome way to configure on a per user basis (so i could add my twitter and diaspora for example into my project chaplin control panel and when i go on a video be able to share/like them good services to support would be:

- Status.net (identi.ca pre-configured?)
- Twitter
- Facebook
- +1 for G+
- Diaspora
others?

**Comment by dandart** [comment]
This exists with twitter the rest should come pretty soon with buttons

**Comment by dandart** [comment]
I just thought - isn't there a plugin for *everything*? Like "AddThis" or something? Would that have pump?

**Comment by dandart** [comment]
Researching addthis-like alternatives

**Comment by dandart** [comment]
Wary of putting addthis actually on it - since this would make the rest not look right with them.

**Comment by dandart** [comment]
Twitter and facebook are on here manually - I still don't know a good reason to use or not to use addthis - other than that it's entirely inconsistent with itself. I suppose others are probably in order in the same fashion.

**Comment by dandart** [comment]
Thinking of using https://github.com/chimo/gs-share for gnusocial...
https://sharetodiaspora.github.io for diaspora...
doing g+ now

**Comment by dandart** [comment]
G+, GnuSocial and Diaspora done... but Pump says "maybe later":
https://github.com/e14n/pump.io/issues/771

Looking into alternatives others have made

**Comment by dandart** [comment]
Looks like the only thing I can find for pump is too integrated - I want to find something a bit more like GnuSocial/Diaspora for that https://gitlab.com/sotitrox/granada

**Comment by dandart** [comment]
Will make new issue for icebox for pump and close this one - for any new networks please create new issues.
