### ISSUE TITLE
YouTube User page does not load extra videos on scroll

### ISSUE THREAD

**Issue by xray7224** [dandart/projectchaplin#69]
When you are looking through videos on a youtube user's page and scroll to the bottom, more video's don't load

Reproduce:

http://projectchaplin.com/user/youtube/id/sxephil

go to the bottom of the page.

**Comment by dandart** [comment]
I'm thinking maybe just having a More button at the bottom or to the right

**Comment by dandart** [comment]
I've removed user favourites as this is uncommon now unless we're talking about your own which we don't currently directly connect to yet anyway.

So can just infinite scroll this I guess

**Comment by dandart** [comment]
Just done it with vimeo as well
